server:
  port: 8083
spring:
  application:
    name: Catalog
#  datasource:
#    url: 'jdbc:postgresql://localhost:15432/postgres?ApplicationName=Catalog'
#    username: 'postgres'
#    password: '123456'
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect

multitenancy:
  master:
    datasource:
      url: jdbc:postgresql://localhost:15432/catalogo
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver
    liquibase:
      changeLog: classpath:db/changelog/db.changelog-master.yaml
  tenant:
    datasource:
      url-prefix: jdbc:postgresql://localhost:15432/
    liquibase:
      changeLog: classpath:db/changelog/db.changelog-tenant.yaml

encryption:
  secret: verySecret
  salt: chezuis