server:
  port: 8080
spring:
  application:
    name: MultiTenant
  datasource:
    url: 'jdbc:postgresql://localhost:15432/postgres?ApplicationName=MultiTenant'
    username: 'postgres'
    password: '123456'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect